services:
  database:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-todo_app}
      # Definitely this is due to changes in production
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!todo_password!}
      - POSTGRES_USER=${POSTGRES_USER:-todo_user}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  fastapi:
    build: ./
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - 8000:80


volumes:
  db_data:
