"""Adding Shared Todo table relations

Revision ID: 21766ed040ad
Revises: 9c60b4841d39
Create Date: 2024-06-04 19:29:08.899143

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "21766ed040ad"
down_revision: Union[str, None] = "9c60b4841d39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
