"""Initiale alembic versions

Revision ID: 25454f0483a1
Revises:
Create Date: 2024-06-03 22:52:28.691656

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "25454f0483a1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
