"""Fixing mapping

Revision ID: 3e7ee7242270
Revises: 62211f0bc128
Create Date: 2024-06-05 04:07:19.302685

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3e7ee7242270"
down_revision: Union[str, None] = "62211f0bc128"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_shared_todo_id"), "shared_todo", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shared_todo_id"), table_name="shared_todo")
    # ### end Alembic commands ###
