"""Adding owner

Revision ID: 6c4bcbfcf5f3
Revises: fb5ae91f33a6
Create Date: 2024-06-04 05:28:39.572024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c4bcbfcf5f3"
down_revision: Union[str, None] = "fb5ae91f33a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("priority", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_task_priority"), "task", ["priority"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_priority"), table_name="task")
    op.drop_column("task", "priority")
    # ### end Alembic commands ###
