"""Adding Shared Todo table

Revision ID: 7aec848d7e41
Revises: aca07b650906
Create Date: 2024-06-04 19:19:42.856744

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7aec848d7e41"
down_revision: Union[str, None] = "aca07b650906"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
