"""Adding Shared Todo table relation

Revision ID: 9c60b4841d39
Revises: 7aec848d7e41
Create Date: 2024-06-04 19:20:47.612931

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9c60b4841d39"
down_revision: Union[str, None] = "7aec848d7e41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
