"""Fixing mapping

Revision ID: a35079ca7c44
Revises: 29c1e3e6409d
Create Date: 2024-06-05 04:20:43.484706

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a35079ca7c44"
down_revision: Union[str, None] = "29c1e3e6409d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "shared_todo", ["user_id", "todo_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "shared_todo", type_="unique")
    # ### end Alembic commands ###
