"""Upgrade owner

Revision ID: a4a4ef4040ce
Revises: 6c4bcbfcf5f3
Create Date: 2024-06-04 05:38:16.980790

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a4a4ef4040ce"
down_revision: Union[str, None] = "6c4bcbfcf5f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
