"""Adding username field to the usertable

Revision ID: c16316bc2a46
Revises: 196464a9a31f
Create Date: 2024-06-04 03:36:12.835950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c16316bc2a46"
down_revision: Union[str, None] = "196464a9a31f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("username", sa.String(), nullable=True))
    op.create_unique_constraint(None, "user", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "username")
    # ### end Alembic commands ###
