"""Adding Shared Todo table into Users

Revision ID: f7fbe5fcd6eb
Revises: 21766ed040ad
Create Date: 2024-06-04 19:34:25.923325

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f7fbe5fcd6eb"
down_revision: Union[str, None] = "21766ed040ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
